version: "3.8"

services:
  cursor-vip:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cursor-vip
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    volumes:
      # Mount configuration directory if needed
      - ./config:/app/config:ro
      # Mount data directory for persistence
      - cursor-vip-data:/app/data
    networks:
      - cursor-vip-network
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
    # Health check
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    container_name: cursor-vip-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - cursor-vip
    networks:
      - cursor-vip-network

volumes:
  cursor-vip-data:
    driver: local

networks:
  cursor-vip-network:
    driver: bridge
